version: '3.8'

services:
  bot:
    build: .
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      REDIS_URL: $(REDIS_URL)
    depends_on:
      - redis

  redis:
    image: redis:6.2
    ports:
      - "${REDIS_PORT}:6379"
