"""Create user_values table

Revision ID: 45ffb6f3afb4
Revises: 
Create Date: 2024-06-14 16:03:47.164238
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45ffb6f3afb4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('created_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_values_id'), 'user_values', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_values_id'), table_name='user_values')
    op.drop_table('user_values')
    # ### end Alembic commands ###